app.py
from flask import Flask, render_template
from routes import routes
import manageDB as mdb


# Lanzar back end
def create_app():
   mdb.init()
   app = Flask(__name__)
   app.register_blueprint(routes)
   return app

if __name__ == '__main__':
   app = create_app()
   
   #TODO: cambiar al desplegar!
   app.run(debug=True)

routes.py
from flask import Blueprint, render_template
import manageDB as db

# En este archivo se guardan todas las rutas tanto dinamicas como estáticas de la página web
# Cada función incorpora los datos correspondientes a cada una de las plantillas

routes = Blueprint('routes', __name__)

# Esta es la ruta base, o index. Es la landing page.
@routes.route('/')
def home():
   return render_template('index.html', header_fruit=db.get_random_fruits()[0][0])

# Aqui es donde está el catalogo y a donde te lleva la página una vez interactuas con la portada
@routes.route('/fruits')
def fruits():
   print(db.get_all_fruits())
   return render_template('fruits.html', fruits=db.get_all_fruits(), header_fruit=db.get_random_fruits()[0][0])

# Sección con información sobre la página y la tienda
@routes.route('/about')
def about():
   return render_template('about.html', header_fruit=db.get_random_fruits()[0][0])

# Página con la información sobre el método de pago
@routes.route('/payment')
def payment():
   return render_template('payment.html', header_fruit=db.get_random_fruits()[0][0])

templates/about.html

{% extends "common.html" %}

{% block content %}


<section class="container my-5">
  <div class="row">
    <div class="col-md-6">
      <img src="https://via.placeholder.com/300" class="img-fluid rounded" alt="Store Owner">
    </div>
    <div class="col-md-6">
      <h2>La fruta de Riesco</h2>
      <p>En fruterias Riesco, nos tomamos en serio la fruta.</p>
      <p>Nuestro control de calidad asegura que cada una de las frutas que entregamos sea perfecta.</p>
      <p class="font-italic">"Me apasiona la fruta."</p>
      <p>- Señor Riesco</p>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-md-6">
      <h2>Equipo de desarrollo</h2>
      <p>Para fruterias Riesco, el equipo de desarrollo es como parte de la familia.</p>
      <p>Compuesto por Cristian Molina, Álvaro Álvarez y Álvaro Corrochano, han realizado un trabajo excelente.</p>
      <p class="font-italic">"Pensamos que la mejor opción era utilizar Flask para el back-end y SQLite para la base de datos."</p>
      <p>- Equipo de desarrollo</p>
    </div>
    <div class="col-md-6 ">
      <img src="https://via.placeholder.com/300" class="img-fluid rounded" alt="Store Owner">
    </div>
  </div>
</section>



{% endblock content %}

templates/common.html
<!--  Este archivo contiene la barra de navegación y el footer. 
      La idea es usar esta plantilla en composición con otras para 
      añadir estas funcionalidades donde se quiera sin tener
      que volver a programarlas. -->

<!DOCTYPE html>
<html>
<head>
 <title>Frutería Riesco</title>
 <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
 <header>
 <nav>
    <div>
      <h3 style="align-self: center;">Fruterias riesco, el {{ header_fruit }} más fresco</li>
      <ul>
        <li><a href="{{ url_for('routes.home') }}">Inicio</a></li>
        <li><a href="{{ url_for('routes.fruits') }}">Frutas</a></li>
        <li ><a href="{{ url_for('routes.about') }}">About</a></li>
        </ul>
    </div>
 </nav>
 </header>
 <main>
  <div>
    <!-- En esta parte es donde se insertará el resto de plantillas html -->
      {% block content %}{% endblock %}
  </div>
</main>
 <footer>
  <p>Frutería &copy; 2023</p>
 </footer>
 <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

templates/fruits.html
{% extends "common.html" %}

{% block content %}

<!-- boton para cambiar el color de las frutas

<button id="change-color-button">Change Color</button>
<script>
    window.onload = function() {
       var fruitNameElements = document.getElementsByClassName('fruit-name');
    
       document.getElementById('toggle-color-button').addEventListener('click', function() {
           for (var i = 0; i < fruitNameElements.length; i++) {
               var fruitNameElement = fruitNameElements[i];
               var originalColor = fruitNameElement.style.color;
               if (fruitNameElement.style.color === 'black') {
                   fruitNameElement.style.color = originalColor;
               } else {
                   fruitNameElement.style.color = 'black';
               }
           }
       });
    };
</script> 
-->


<div class="container mt-5">
  <div class="row">
      {% for fruit in fruits %}
          <div class="col-md-4 mb-4">
            <img src="{{ fruit[4] }}" class="card-img-top" alt="Product">
              <div class="card">
                  <div class="card-body">
                      <h5 class="card-title fruit-name" style="color: {{fruit[2]}};">{{ fruit[1] }}</h5>
                      <p class="card-text">{{ fruit[3] }}€/u</p>
                      <div class="form-inline">
                          <label for="quantity" class="mr-2">Quantity:</label>
                          <input type="number" id="quantity" class="form-control mr-2" />
                      </div>
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>
  <div class="row justify-content-center">
    <div class="col-md-6">
        <h2 class="mb-4">Payment Details</h2>
        <form>
            <div class="form-group">
              <label for="cardNumber">Full name</label>
              <input type="text" class="form-control" id="fullName" placeholder="Enter Full Name" required>
            </div>
            <div class="form-group">
                <label for="cardNumber">Card Number</label>
                <input type="text" class="form-control" id="cardNumber" placeholder="Enter card number" required>
            </div>
            <div class="form-group">
                <label for="expirationDate">Expiration Date</label>
                <input type="text" class="form-control" id="expirationDate" placeholder="MM/YYYY" required>
            </div>
            <div class="form-group">
                <label for="cvv">CVV</label>
                <input type="text" class="form-control" id="cvv" placeholder="Enter CVV" required>
            </div>
            <button type="submit" class="btn btn-primary mb-5" onclick="window.location.href='payment'">Pay Now</button>
        </form>
    </div>
</div>
</div>
<br>
<script src="{{ url_for('static', filename='script.js') }}"></script>

{% endblock content %}

templates/index.html

<header>
</header>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<style>
  body {
    background-image: url({{ url_for('static', filename='background.jpg') }});
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: 100% 100%;
  }
</style>


<body>

  <div class="ml-5 mt-5">
    <h1 style="font-size: 100px; color: #006064"> Frutería Riesco </h1>
  </div>
  <div class="ml-5 mt-5">
    <h2 style="font-size: 50px; color: #006064"> El {{ header_fruit }} más fresco! </h1>
  </div>
  <div class="ml-5 mt-5">
    <div style="font-size: 32px; color: #006064"> Descubre nuestras deliciosas frutas y verduras!  </h1>
  </div>

  <div >
    <button type="button" class="btn btn-light mt-5" style="background-color: #006064; color:white" onclick="window.location.href='fruits'">Conoce nuestros productos</button>
  </div>

</body>

templates/payment.html
{% extends "common.html" %}

{% block content %}

<section class="container my-5">
    <div class="alert alert-success" role="alert">
      <h4 class="alert-heading">Pedido realizado satisfactoriamente!</h4>
      <p>Gracias pro comprar en frutería Riesco. Los datos de tu pedido se han guardado y serán revisados manualmente por el señor Riesco. Recibirá 
        información sobre su pedido proximamente.</p>
      <hr>
      <p class="mb-0">Si tiene alguna duda, no dude en contactar con el señor Riesco.</p>
    </div>
  </section>

{% endblock content %}